global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'symfony-project'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'mysql-exporter:9104' ]