version: "3.5"

services:

  php:
    container_name: symfony_php
    restart: unless-stopped
    ports:
      - "8000:8000"
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    volumes:
      - .:/app
    depends_on:
      - prometheus
    networks:
      - symfony_network
    command: symfony serve --dir=./public --port=8000


  mysql:
    container_name: mysql
    image: mysql:8.2
    restart: always
    ports:
      - "3336:3306"
    environment:
      MYSQL_DATABASE: symfony_database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - symfony_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.48.0
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    networks:
      - symfony_network

  mysqld_exporter:
    container_name: mysqld_exporter
    build:
      context: ./docker/mysqld_exporter
    user: root
    ports:
      - "9104:9104"
    restart: unless-stopped
    command:
      - "--mysqld.username=root:root"
      - "--mysqld.address=mysql:3306"
    environment:
      - "collect.info_schema.tablestats=true"
      - "collect.info_schema.userstats=true"
      - "collect.info_schema.query_response_time=true"
      - "collect.auto_increment.columns=true"
      - "collect.perf_schema.tableiowaits=true"
      - "collect.perf_schema.tablelocks=true"
    depends_on:
      - mysql
    networks:
      - symfony_network

  grafana:
    container_name: grafana
    build:
      context: ./docker/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./docker/grafana/provisioning/datasource.yml:/etc/grafana/provisioning/datasource.yml"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_PASSWORD=123456
    networks:
      - symfony_network

  redis:
    container_name: redis
    image: redis:7.0.9
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - symfony_network

  redis_exporter:
    container_name: redis_exporter
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - symfony_network

networks:
  symfony_network:

volumes:
  mysql_data:
  redis_data:


