version: "3.5"

services:

  symfony-php:
    container_name: symfony-php
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    volumes:
      - .:/app
    networks:
      - symfony-network

  symfony-nginx:
    container_name: symfony-nginx
    build:
      context: ./docker/nginx
    volumes:
      - .:/app
    ports:
      - "8080:80"
    depends_on:
      - symfony-php
    networks:
      - symfony-network

  symfony-mysql:
    container_name: symfony-mysql
    image: mysql:latest
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: symfony-database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - symfony-mysql-data:/var/lib/mysql
    networks:
      - symfony-network
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]

networks:
  symfony-network:

volumes:
  symfony-mysql-data:


