version: "3.5"

services:

  symfony_php:
    container_name: symfony_php
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    volumes:
      - .:/app
    networks:
      - symfony_network

  symfony_nginx:
    container_name: symfony_nginx
    build:
      context: ./docker/nginx
    volumes:
      - .:/app
    ports:
      - "8080:80"
    depends_on:
      - symfony_php
    networks:
      - symfony_network

  symfony_mysql:
    container_name: symfony_mysql
    image: mysql:latest
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: symfony_database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - symfony_mysql_data:/var/lib/mysql
    networks:
      - symfony_network
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]

networks:
  symfony_network:

volumes:
  symfony_mysql_data:


