services:
  _defaults:
    autowire: true
    autoconfigure: true

  Common\:
    resource: "../../../../../Common"

  Common\Infrastructure\Adapter\REST\Symfony\Listener\JsonTransformerExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  #DependencyInyection
  Common\Infrastructure\Adapter\REST\Symfony\Resolver\:
    resource: '../../../../../Common/Infrastructure/Adapter/REST/Symfony/Resolver'
    tags: [ 'controller.service_arguments' ]

