services:
  _defaults:
    autowire: true
    autoconfigure: true

  common.domain_event_suscriber:
    class: Common\Domain\Bus\Event\DomainEventSubscriberInterface

  _instanceof:
    Common\Domain\Bus\Event\DomainEventSubscriberInterface:
      tags: [ 'common.domain_event_subscriber' ]

  Common\:
    resource: "../../../../../Common"

  Common\Infrastructure\Adapter\REST\Symfony\Listener\JsonTransformerExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  Common\Infrastructure\Adapter\REST\Symfony\Resolver\:
    resource: '../../../../../Common/Infrastructure/Adapter/REST/Symfony/Resolver'
    tags: [ 'controller.service_arguments' ]

  Common\Infrastructure\Bus\Event\Symfony\InMemory\InMemorySymfonyEventBus:
    arguments: [ !tagged common.domain_event_subscriber ]
    lazy: true