# config/routes/annotations.yaml
home_ui_controllers:
  resource: ../../src/Home/Infrastructure/UI/Symfony/Controller
  type: annotation

home_controllers:
  resource: ../../src/Home/Infrastructure/REST/Symfony/Controller
  type: annotation

user_controllers:
  resource: ../../src/User/Infrastructure/Adapter/REST/Symfony/Controller
  prefix: user
  type: annotation