# config/routes/annotations.yaml
api_controllers:
    resource: ../../src/Api/Adapter/Framework/HTTP/Controller
    type: annotation


user_controllers:
    resource: ../../src/User/Adapter/Framework/HTTP/Controller
    prefix: user
    type: annotation