# config/routes/annotations.yaml
api_controllers:
    resource: ../../src/Common/Infrastructure/Adapter/UI/Controller
    type: annotation


user_controllers:
    resource: ../../src/User/Infrastructure/Adapter/REST/Controller
    prefix: user
    type: annotation