imports:
  - { resource: '../src/Home/Infrastructure/Config/Symfony/Service/home.yaml' }
  - { resource: '../src/User/Infrastructure/Config/Symfony/Service/user.yaml' }
  - { resource: '../src/Common/Infrastructure/Config/Symfony/Service/common.yaml' }
