### getUserById
GET {{host}}/api/user/get/c08a0431-e82c-4fc5-82f7-7cd84cc251d1
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### register - method to create a user
POST {{host}}/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "wel3lcom3e",
  "password": "wellcome_password"
}
###

### loginCheck
POST {{host}}/login_check
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "wel3lcom3e",
  "password": "wellcome_password"
}
###