### getUserById
GET {{host}}/user/get/3
Content-Type: application/json

### createUser - method to create a user
POST {{host}}/user/create
Content-Type: application/json

{
  "username": "penelsop5sassdedd2",
  "password": "passwsaord"
}
###