services:
  _defaults:
    autowire: true
    autoconfigure: true

  Api\:
    resource: "../../../../../Api"

  Api\Adapter\Framework\Listener\JsonTransformerExceptionListener:
    tags:
#      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
