services:
  _defaults:
    autowire: true
    autoconfigure: true

  User\:
    resource: "../../../../../User"
    exclude:
      - "../../../../../User/Domain/Model"

  User\Adapter\Framework\HTTP\Controller\:
    resource: '../../../../../User/Adapter/Framework/HTTP/Controller'
    tags: [ 'controller.service_arguments' ]
